#!/bin/sh

cd `dirname $0`

set -e
echo "Initial preparation...this can take awhile, so sit tight..."
libtoolize --automake --copy --force
aclocal
autoheader
automake --foreign --add-missing --copy
autoconf

echo "You are now ready to run ./configure ..."

