#!/bin/bash
#
#  Install script for the ParaGUI sample application
#  Builds and installs the binary

ml_check_for_package paragui


CONFIGOPTIONS="--prefix=$TOOLS --with-sdl-prefix=$TOOLS --disable-paraguitest $TARGETARCH"
COMPILEOPTIONS=

function ml_installlocal() {
        $JMAKE -C $PACKAGE/$PACKAGE prefix="$TOOLS" install-strip
}

function ml_installroot() {
        for i in paratest ; do
            cp -af $TOOLS/bin/${i} $ROOT/usr/bin
        done

	ml_transpose $BUILD/paratest-1.0.0/init.d/gui $ROOT/usr/init.d/gui 755
}
